name: Supprimer branches fusionnées

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-merged-branch:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Supprimer la branche source
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Récupère le nom de la branche head de la PR
            const branch = context.payload.pull_request.head.ref;

            // Supprime la référence Git correspondante
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branch}`
            });
