name: Supprimer branches fusionnées

on:
  pull_request:
    types: [closed]

permissions:
  contents: write  # nécessaire pour supprimer la branche

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Supprimer la branche source
        uses: peter-evans/delete-branch@v2
        with:
          branch: ${{ github.event.pull_request.head.ref }}
