# .github/workflows/comment-codecov-ai.yml
name: Commenter les instructions Codecov AI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  comment-codecov-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Codecov AI Instructions
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CODECOV_TOKEN }}
          script: |
            // On prépare le corps du commentaire dans une variable pour gérer proprement
            // les backticks JavaScript
            const commentBody = `**Utilisation de Codecov AI**

- **Revue de PR** : ajoutez \`@codecov-ai-reviewer review\`.
- **Génération de tests** : ajoutez \`@codecov-ai-reviewer test\`.`;

            // On poste le commentaire sur la PR
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
