name: Commenter les instructions Codecov AI

# 1. Permissions explicites
permissions:
  contents: read           # pour checkout
  issues: write            # pour createComment
  pull-requests: write     # si nécessaire

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment-codecov-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Poster les instructions Codecov AI
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `**Utilisation de Codecov AI**

            - **Revue de PR** : ajoutez \`@codecov-ai-reviewer review\`.
            - **Génération de tests** : ajoutez \`@codecov-ai-reviewer test\`.`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
